services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db_data:/db_data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////db_data/tradingjournalapp.db
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        echo '=== DATABASE DEBUG INFO ===';
        echo 'Current directory:' && pwd;
        echo 'Database directory contents:' && ls -la /db_data;
        echo 'Database file permissions:' && ls -la /db_data/tradingjournalapp.db;
        echo 'Database URL:' && echo \$DATABASE_URL;
        echo 'Starting application...';
        uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
