services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///tradingjournalapp.db
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-new/src:/app/src  # Only mount the src directory
      - ./frontend-new/public:/app/public  # Mount public directory if needed
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always