services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db_data:/db_data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////db_data/tradingjournalapp.db
      - USE_FIRESTORE=true
      - FIREBASE_PROJECT_ID=tradelogix-9f574
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
      - PYTHONUNBUFFERED=1
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always
    command: npm run start
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
