# Using Firebase/Firestore for database - No local volumes needed
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./db_data:/db_data
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:////db_data/tradingjournalapp.db
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend-new:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm start
