services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///tradingjournalapp.db
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
