# Use Node.js 16
FROM node:16-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./
COPY vite.config.js ./

# Install dependencies
RUN npm install

# Expose port
EXPOSE 3000

# Start Vite server
CMD ["npm", "start"]
